version: '3.8'

services:
  # PostgreSQL Database for Test Environment
  postgres-test:
    image: postgres:15-alpine
    container_name: autotest-postgres-test
    environment:
      POSTGRES_DB: autotest_testing
      POSTGRES_USER: autotest_test_user
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-autotest_test_password}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autotest_test_user -d autotest_testing"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - autotest-test-network

  # Backend API for Test Environment
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: autotest-backend-test
    environment:
      NODE_ENV: testing
      DATABASE_URL: postgresql://autotest_test_user:${POSTGRES_TEST_PASSWORD:-autotest_test_password}@postgres-test:5432/autotest_testing
      JWT_SECRET: ${JWT_SECRET_TEST:-test_jwt_secret_key_for_testing_environment}
      PORT: 4001  # Different port
      # GitHub OAuth Configuration (can use same or different credentials)
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID_TEST:-${GITHUB_CLIENT_ID}}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET_TEST:-${GITHUB_CLIENT_SECRET}}
      GITHUB_CALLBACK_URL: ${FRONTEND_TEST_URL}/api/github/callback
      TEAM_GITHUB_CALLBACK_URL: ${FRONTEND_TEST_URL}/api/teams/callback/github
      FRONTEND_URL: ${FRONTEND_TEST_URL:-http://localhost:3001}
    ports:
      - "4001:4001"  # Different port
    depends_on:
      postgres-test:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ./start.sh
    networks:
      - autotest-test-network

  # Frontend React App for Test Environment
  frontend-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autotest-frontend-test
    environment:
      REACT_APP_API_URL: http://backend-test:4001/api
      NODE_ENV: testing
    ports:
      - "3001:3000"  # Map container port 3000 to host port 3001
    depends_on:
      - backend-test
    networks:
      - autotest-test-network

volumes:
  postgres_test_data:

networks:
  autotest-test-network:
    driver: bridge
