name: API Test Pipeline (Supertest + Karate + REST Assured)

on:
  workflow_dispatch:
    inputs:
      run_supertest:
        description: 'Run Supertest API tests'
        required: false
        default: true
        type: boolean
      run_karate:
        description: 'Run Karate-style API tests'
        required: false
        default: true
        type: boolean
      run_restassured:
        description: 'Run REST Assured-style API tests'
        required: false
        default: true
        type: boolean
      backend_url:
        description: 'Backend URL for API tests'
        required: false
        default: 'http://localhost:4000'
        type: string

jobs:
  setup-backend:
    name: Setup Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Start backend server
        run: |
          cd backend
          npm start &
          sleep 10
          echo "Backend started at http://localhost:4000"

      - name: Wait for backend to be ready
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:4000/health; then
              echo "Backend is ready"
              break
            fi
            echo "Waiting for backend... ($i/30)"
            sleep 2
          done

  api-tests-supertest:
    name: API Tests (Supertest)
    runs-on: ubuntu-latest
    needs: setup-backend
    if: ${{ github.event.inputs.run_supertest == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Supertest API tests
        run: npm run test:api:supertest
        env:
          TEST_API_URL: ${{ github.event.inputs.backend_url }}

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: supertest-api-results
          path: ./coverage/supertest-api-results.json

  api-tests-karate:
    name: API Tests (Karate-style)
    runs-on: ubuntu-latest
    needs: setup-backend
    if: ${{ github.event.inputs.run_karate == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Karate-style API tests
        run: npm run test:api:karate
        env:
          TEST_API_URL: ${{ github.event.inputs.backend_url }}

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: karate-api-results
          path: ./coverage/karate-api-results.json

  api-tests-restassured:
    name: API Tests (REST Assured-style)
    runs-on: ubuntu-latest
    needs: setup-backend
    if: ${{ github.event.inputs.run_restassured == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run REST Assured-style API tests
        run: npm run test:api:restassured
        env:
          TEST_API_URL: ${{ github.event.inputs.backend_url }}

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: restassured-api-results
          path: ./coverage/restassured-api-results.json

  test-results-parser:
    name: Parse and Combine API Test Results
    runs-on: ubuntu-latest
    needs: [api-tests-supertest, api-tests-karate, api-tests-restassured]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          path: ./coverage/

      - name: Parse test results
        run: |
          node -e "
          const { TestResultsParser } = require('./src/utils/testResultsParser.js');
          const parser = new TestResultsParser();
          
          // Parse results from each framework
          const supertestResults = parser.parseResults('supertest', 'api', './coverage/supertest-api-results.json');
          const karateResults = parser.parseResults('karate', 'api', './coverage/karate-api-results.json');
          const restassuredResults = parser.parseResults('restassured', 'api', './coverage/restassured-api-results.json');
          
          // Generate unified report
          const unifiedReport = parser.generateUnifiedReport([supertestResults, karateResults, restassuredResults]);
          
          // Save unified report
          require('fs').writeFileSync('./reports/unified-api-test-report.json', JSON.stringify(unifiedReport, null, 2));
          console.log('Unified API test report generated');
          "

      - name: Upload unified test report
        uses: actions/upload-artifact@v3
        with:
          name: unified-api-test-report
          path: ./reports/unified-api-test-report.json

  notify-results:
    name: Notify API Test Results
    runs-on: ubuntu-latest
    needs: [api-tests-supertest, api-tests-karate, api-tests-restassured, test-results-parser]
    if: always()
    steps:
      - name: Download unified test report
        uses: actions/download-artifact@v3
        with:
          name: unified-api-test-report

      - name: Parse results for notification
        id: results
        run: |
          if [ -f "./unified-api-test-report.json" ]; then
            TOTAL_TESTS=$(jq '.summary.total' unified-api-test-report.json)
            PASSED_TESTS=$(jq '.summary.passed' unified-api-test-report.json)
            FAILED_TESTS=$(jq '.summary.failed' unified-api-test-report.json)
            SUCCESS_RATE=$(echo "scale=1; $PASSED_TESTS * 100 / $TOTAL_TESTS" | bc)
            
            echo "total=$TOTAL_TESTS" >> $GITHUB_OUTPUT
            echo "passed=$PASSED_TESTS" >> $GITHUB_OUTPUT
            echo "failed=$FAILED_TESTS" >> $GITHUB_OUTPUT
            echo "success_rate=$SUCCESS_RATE" >> $GITHUB_OUTPUT
          else
            echo "total=0" >> $GITHUB_OUTPUT
            echo "passed=0" >> $GITHUB_OUTPUT
            echo "failed=0" >> $GITHUB_OUTPUT
            echo "success_rate=0" >> $GITHUB_OUTPUT
          fi

      - name: Notify Slack
        if: ${{ steps.results.outputs.failed > 0 }}
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: |
            API Test Pipeline Failed! 
            Total: ${{ steps.results.outputs.total }}
            Passed: ${{ steps.results.outputs.passed }}
            Failed: ${{ steps.results.outputs.failed }}
            Success Rate: ${{ steps.results.outputs.success_rate }}%
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack Success
        if: ${{ steps.results.outputs.failed == 0 }}
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: |
            API Test Pipeline Passed! 
            Total: ${{ steps.results.outputs.total }}
            Passed: ${{ steps.results.outputs.passed }}
            Success Rate: ${{ steps.results.outputs.success_rate }}%
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
