name: CI/CD Pipeline 3 - Python Focus

on:
  workflow_dispatch:
    inputs:
      run_unit_tests:
        description: 'Run Unit Tests (pytest)'
        required: false
        default: true
        type: boolean
      run_integration_tests:
        description: 'Run Integration Tests (pytest + requests)'
        required: false
        default: true
        type: boolean
      run_api_tests:
        description: 'Run API Tests (Karate)'
        required: false
        default: true
        type: boolean
      run_e2e_tests:
        description: 'Run E2E Tests (Selenium WebDriver)'
        required: false
        default: true
        type: boolean
      test_flakiness:
        description: 'Enable flakiness testing (random pass/fail)'
        required: false
        default: true
        type: boolean
      backend_url:
        description: 'Backend URL for tests'
        required: false
        default: 'http://localhost:4000'
        type: string

jobs:
  setup-backend:
    name: Setup Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Start backend server
        run: |
          cd backend
          npm start &
          sleep 10
          echo "Backend started at http://localhost:4000"

      - name: Wait for backend to be ready
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:4000/health; then
              echo "Backend is ready"
              break
            fi
            echo "Waiting for backend... ($i/30)"
            sleep 2
          done

  unit-tests-pytest:
    name: Unit Tests (pytest)
    runs-on: ubuntu-latest
    needs: setup-backend
    if: ${{ github.event.inputs.run_unit_tests == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest unit tests
        run: |
          if [ "${{ github.event.inputs.test_flakiness }}" = "true" ]; then
            echo "Running pytest tests with flakiness simulation..."
            npm run test:unit:pytest:mock
          else
            echo "Running pytest tests normally..."
            npm run test:unit:pytest
          fi
        env:
          ENABLE_FLAKINESS: ${{ github.event.inputs.test_flakiness }}

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-unit-results
          path: |
            ./pytest-results.xml
            ./coverage/pytest-coverage.json
            ./htmlcov/

  integration-tests-pytest:
    name: Integration Tests (pytest + requests)
    runs-on: ubuntu-latest
    needs: setup-backend
    if: ${{ github.event.inputs.run_integration_tests == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest integration tests
        run: |
          if [ "${{ github.event.inputs.test_flakiness }}" = "true" ]; then
            echo "Running pytest integration tests with flakiness simulation..."
            npm run test:integration:pytest:mock
          else
            echo "Running pytest integration tests normally..."
            npm run test:integration:pytest
          fi
        env:
          TEST_API_URL: ${{ github.event.inputs.backend_url }}
          ENABLE_FLAKINESS: ${{ github.event.inputs.test_flakiness }}

      - name: Upload pytest integration test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-integration-results
          path: |
            ./pytest-integration-results.xml
            ./coverage/pytest-integration-coverage.json

  api-tests-karate:
    name: API Tests (Karate)
    runs-on: ubuntu-latest
    needs: setup-backend
    if: ${{ github.event.inputs.run_api_tests == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Karate API tests
        run: |
          if [ "${{ github.event.inputs.test_flakiness }}" = "true" ]; then
            echo "Running Karate tests with flakiness simulation..."
            npm run test:api:karate:mock
          else
            echo "Running Karate tests normally..."
            npm run test:api:karate
          fi
        env:
          TEST_API_URL: ${{ github.event.inputs.backend_url }}
          ENABLE_FLAKINESS: ${{ github.event.inputs.test_flakiness }}

      - name: Upload Karate test results
        uses: actions/upload-artifact@v3
        with:
          name: karate-api-results
          path: |
            ./target/surefire-reports/
            ./target/karate-results.xml

  e2e-tests-selenium:
    name: E2E Tests (Selenium WebDriver)
    runs-on: ubuntu-latest
    needs: setup-backend
    if: ${{ github.event.inputs.run_e2e_tests == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Selenium E2E tests
        run: |
          if [ "${{ github.event.inputs.test_flakiness }}" = "true" ]; then
            echo "Running Selenium tests with flakiness simulation..."
            npm run test:e2e:selenium:mock
          else
            echo "Running Selenium tests normally..."
            npm run test:e2e:selenium
          fi
        env:
          TEST_API_URL: ${{ github.event.inputs.backend_url }}
          ENABLE_FLAKINESS: ${{ github.event.inputs.test_flakiness }}

      - name: Upload Selenium test results
        uses: actions/upload-artifact@v3
        with:
          name: selenium-e2e-results
          path: |
            ./coverage/selenium-results.json
            ./screenshots/

  analyze-flakiness:
    name: Analyze Test Flakiness
    runs-on: ubuntu-latest
    needs: [unit-tests-pytest, integration-tests-pytest, api-tests-karate, e2e-tests-selenium]
    if: ${{ github.event.inputs.test_flakiness == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all test results
        uses: actions/download-artifact@v3
        with:
          path: ./test-results

      - name: Analyze flakiness patterns
        run: |
          echo "Analyzing test flakiness patterns..."
          node scripts/analyze-flakiness.js pipeline3
        env:
          TEST_RESULTS_PATH: ./test-results

      - name: Upload flakiness report
        uses: actions/upload-artifact@v3
        with:
          name: flakiness-analysis-pipeline3
          path: ./flakiness-report.json
