name: CI/CD Pipeline 2 - Tap + Cypress + Karate + JMeter

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - staging
        - production
      run_all_tests:
        description: 'Run all test types'
        required: false
        default: true
        type: boolean
      run_unit_tests:
        description: 'Run unit tests only'
        required: false
        default: false
        type: boolean
      run_integration_tests:
        description: 'Run integration tests only'
        required: false
        default: false
        type: boolean
      run_api_tests:
        description: 'Run API tests only'
        required: false
        default: false
        type: boolean
      run_e2e_tests:
        description: 'Run E2E tests only'
        required: false
        default: false
        type: boolean
      run_performance_tests:
        description: 'Run performance tests only'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '18'
  TEST_ENVIRONMENT_URL: ${{ secrets.TEST_ENVIRONMENT_URL }}
  TEST_ENVIRONMENT_IP: ${{ secrets.TEST_ENVIRONMENT_IP }}
  TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
  TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

jobs:
  # Job 1: Code Quality & Linting
  code-quality:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  # Job 2: Unit Tests (Tap/JUnit-style)
  unit-tests:
    name: Unit Tests (Tap)
    runs-on: ubuntu-latest
    needs: code-quality
    if: ${{ github.event.inputs.run_all_tests == 'true' || github.event.inputs.run_unit_tests == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with Tap
        run: npm run test:unit:tap

      - name: Generate coverage report
        run: npm run test:coverage:tap

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/coverage-final.json
          flags: unit-tap
          name: unit-coverage-tap

  # Job 3: Integration Tests (Tap)
  integration-tests:
    name: Integration Tests (Tap)
    runs-on: ubuntu-latest
    needs: code-quality
    if: ${{ github.event.inputs.run_all_tests == 'true' || github.event.inputs.run_integration_tests == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests with Tap
        run: npm run test:integration:tap

  # Job 4: API Tests (Karate-style)
  api-tests:
    name: API Tests (Karate-style)
    runs-on: ubuntu-latest
    needs: code-quality
    if: ${{ github.event.inputs.run_all_tests == 'true' || github.event.inputs.run_api_tests == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run API tests with Karate-style
        run: npm run test:api:karate

  # Job 5: Deploy to Test Environment
  deploy-test:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, api-tests]
    if: ${{ github.event.inputs.run_all_tests == 'true' || github.event.inputs.run_e2e_tests == 'true' || github.event.inputs.run_performance_tests == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Deploy to EC2 Test Environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.TEST_ENVIRONMENT_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /opt/autotest
            git pull origin main
            docker-compose -f docker-compose.test.yml down
            docker-compose -f docker-compose.test.yml build --no-cache
            docker-compose -f docker-compose.test.yml up -d
            docker-compose -f docker-compose.test.yml exec backend node scripts/migrate.js
            echo "Deployment completed successfully"

      - name: Wait for deployment
        run: |
          sleep 30
          echo "Waiting for services to be ready..."

  # Job 6: E2E Tests (Cypress)
  e2e-tests:
    name: E2E Tests (Cypress)
    runs-on: ubuntu-latest
    needs: deploy-test
    if: ${{ github.event.inputs.run_all_tests == 'true' || github.event.inputs.run_e2e_tests == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress
        run: npm install cypress

      - name: Setup test environment variables
        run: |
          echo "TEST_TARGET_URL=${{ env.TEST_ENVIRONMENT_URL }}" >> $GITHUB_ENV
          echo "TEST_API_URL=${{ env.TEST_ENVIRONMENT_URL }}/api" >> $GITHUB_ENV

      - name: Run E2E tests with Cypress
        run: |
          npx cypress run --reporter junit --reporter-options mochaFile=reports/cypress-results.xml
        env:
          TEST_TARGET_URL: ${{ env.TEST_ENVIRONMENT_URL }}
          TEST_API_URL: ${{ env.TEST_ENVIRONMENT_URL }}/api
          TEST_USER_EMAIL: ${{ env.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ env.TEST_USER_PASSWORD }}

      - name: Upload Cypress test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-results
          path: reports/cypress-results.xml
          retention-days: 30

  # Job 7: Performance Tests (JMeter)
  performance-tests:
    name: Performance Tests (JMeter)
    runs-on: ubuntu-latest
    needs: deploy-test
    if: ${{ github.event.inputs.run_all_tests == 'true' || github.event.inputs.run_performance_tests == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.3.tgz
          tar -xzf apache-jmeter-5.4.3.tgz

      - name: Setup test environment variables
        run: |
          echo "TEST_TARGET_URL=${{ env.TEST_ENVIRONMENT_URL }}" >> $GITHUB_ENV
          echo "TEST_API_URL=${{ env.TEST_ENVIRONMENT_URL }}/api" >> $GITHUB_ENV

      - name: Run performance tests with JMeter
        run: |
          ./apache-jmeter-5.4.3/bin/jmeter -n -t tests/performance/jmeter-load-test.jmx -l reports/jmeter-results.jtl -e -o reports/jmeter-report
        env:
          TEST_TARGET_URL: ${{ env.TEST_ENVIRONMENT_URL }}
          TEST_API_URL: ${{ env.TEST_ENVIRONMENT_URL }}/api

      - name: Upload JMeter test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: jmeter-results
          path: |
            reports/jmeter-results.jtl
            reports/jmeter-report/
          retention-days: 30

  # Job 8: Test Results Summary
  test-results:
    name: Test Results Summary (Pipeline 2)
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, api-tests, e2e-tests, performance-tests]
    if: always()
    steps:
      - name: Generate test summary
        run: |
          echo "## Test Results Summary - Pipeline 2" >> $GITHUB_STEP_SUMMARY
          echo "### Unit Tests (Tap): ${{ needs.unit-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "### Integration Tests (Tap): ${{ needs.integration-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "### API Tests (Karate-style): ${{ needs.api-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "### E2E Tests (Cypress): ${{ needs.e2e-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "### Performance Tests (JMeter): ${{ needs.performance-tests.result }}" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.unit-tests.result }}" == "success" ] && [ "${{ needs.integration-tests.result }}" == "success" ] && [ "${{ needs.api-tests.result }}" == "success" ] && [ "${{ needs.e2e-tests.result }}" == "success" ] && [ "${{ needs.performance-tests.result }}" == "success" ]; then
            echo "✅ All tests passed in Pipeline 2!" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Some tests failed in Pipeline 2. Please check the logs above." >> $GITHUB_STEP_SUMMARY
          fi
