name: E2E Test Pipeline (Playwright + Cypress + Selenium)

on:
  workflow_dispatch:
    inputs:
      run_playwright:
        description: 'Run Playwright E2E tests'
        required: false
        default: true
        type: boolean
      run_cypress:
        description: 'Run Cypress E2E tests'
        required: false
        default: true
        type: boolean
      run_selenium:
        description: 'Run Selenium E2E tests'
        required: false
        default: true
        type: boolean
      target_url:
        description: 'Target URL for E2E tests'
        required: false
        default: 'http://localhost:5173'
        type: string

jobs:
  setup-environment:
    name: Setup Test Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start application
        run: |
          npm run preview &
          sleep 10
          echo "Application started at http://localhost:4173"

      - name: Wait for application to be ready
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:4173; then
              echo "Application is ready"
              break
            fi
            echo "Waiting for application... ($i/30)"
            sleep 2
          done

  e2e-tests-playwright:
    name: E2E Tests (Playwright)
    runs-on: ubuntu-latest
    needs: setup-environment
    if: ${{ github.event.inputs.run_playwright == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright E2E tests
        run: npm run test:e2e:playwright
        env:
          TEST_TARGET_URL: ${{ github.event.inputs.target_url }}

      - name: Upload Playwright results
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: ./playwright-report/

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-results
          path: ./coverage/playwright-results.json

  e2e-tests-cypress:
    name: E2E Tests (Cypress)
    runs-on: ubuntu-latest
    needs: setup-environment
    if: ${{ github.event.inputs.run_cypress == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress E2E tests
        run: npm run test:e2e:cypress
        env:
          CYPRESS_baseUrl: ${{ github.event.inputs.target_url }}

      - name: Upload Cypress results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: ./cypress/videos/
          if-no-files-found: ignore

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: ./coverage/cypress-results.json

  e2e-tests-selenium:
    name: E2E Tests (Selenium)
    runs-on: ubuntu-latest
    needs: setup-environment
    if: ${{ github.event.inputs.run_selenium == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Selenium E2E tests
        run: npm run test:e2e:selenium
        env:
          TEST_TARGET_URL: ${{ github.event.inputs.target_url }}

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: selenium-test-results
          path: ./coverage/selenium-results.json

  test-results-parser:
    name: Parse and Combine E2E Test Results
    runs-on: ubuntu-latest
    needs: [e2e-tests-playwright, e2e-tests-cypress, e2e-tests-selenium]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          path: ./coverage/

      - name: Parse test results
        run: |
          node -e "
          const { TestResultsParser } = require('./src/utils/testResultsParser.js');
          const parser = new TestResultsParser();
          
          // Parse results from each framework
          const playwrightResults = parser.parseResults('playwright', 'e2e', './coverage/playwright-results.json');
          const cypressResults = parser.parseResults('cypress', 'e2e', './coverage/cypress-results.json');
          const seleniumResults = parser.parseResults('selenium', 'e2e', './coverage/selenium-results.json');
          
          // Generate unified report
          const unifiedReport = parser.generateUnifiedReport([playwrightResults, cypressResults, seleniumResults]);
          
          // Save unified report
          require('fs').writeFileSync('./reports/unified-e2e-test-report.json', JSON.stringify(unifiedReport, null, 2));
          console.log('Unified E2E test report generated');
          "

      - name: Upload unified test report
        uses: actions/upload-artifact@v3
        with:
          name: unified-e2e-test-report
          path: ./reports/unified-e2e-test-report.json

  notify-results:
    name: Notify E2E Test Results
    runs-on: ubuntu-latest
    needs: [e2e-tests-playwright, e2e-tests-cypress, e2e-tests-selenium, test-results-parser]
    if: always()
    steps:
      - name: Download unified test report
        uses: actions/download-artifact@v3
        with:
          name: unified-e2e-test-report

      - name: Parse results for notification
        id: results
        run: |
          if [ -f "./unified-e2e-test-report.json" ]; then
            TOTAL_TESTS=$(jq '.summary.total' unified-e2e-test-report.json)
            PASSED_TESTS=$(jq '.summary.passed' unified-e2e-test-report.json)
            FAILED_TESTS=$(jq '.summary.failed' unified-e2e-test-report.json)
            SUCCESS_RATE=$(echo "scale=1; $PASSED_TESTS * 100 / $TOTAL_TESTS" | bc)
            
            echo "total=$TOTAL_TESTS" >> $GITHUB_OUTPUT
            echo "passed=$PASSED_TESTS" >> $GITHUB_OUTPUT
            echo "failed=$FAILED_TESTS" >> $GITHUB_OUTPUT
            echo "success_rate=$SUCCESS_RATE" >> $GITHUB_OUTPUT
          else
            echo "total=0" >> $GITHUB_OUTPUT
            echo "passed=0" >> $GITHUB_OUTPUT
            echo "failed=0" >> $GITHUB_OUTPUT
            echo "success_rate=0" >> $GITHUB_OUTPUT
          fi

      - name: Notify Slack
        if: ${{ steps.results.outputs.failed > 0 }}
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: |
            E2E Test Pipeline Failed! 
            Total: ${{ steps.results.outputs.total }}
            Passed: ${{ steps.results.outputs.passed }}
            Failed: ${{ steps.results.outputs.failed }}
            Success Rate: ${{ steps.results.outputs.success_rate }}%
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack Success
        if: ${{ steps.results.outputs.failed == 0 }}
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: |
            E2E Test Pipeline Passed! 
            Total: ${{ steps.results.outputs.total }}
            Passed: ${{ steps.results.outputs.passed }}
            Success Rate: ${{ steps.results.outputs.success_rate }}%
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
