name: Unit Test Pipeline (Vitest + Jest + AVA)

on:
  workflow_dispatch:
    inputs:
      run_vitest:
        description: 'Run Vitest unit tests'
        required: false
        default: true
        type: boolean
      run_jest:
        description: 'Run Jest unit tests'
        required: false
        default: true
        type: boolean
      run_ava:
        description: 'Run AVA unit tests'
        required: false
        default: true
        type: boolean
      run_coverage:
        description: 'Generate coverage reports'
        required: false
        default: true
        type: boolean

jobs:
  unit-tests-vitest:
    name: Unit Tests (Vitest)
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_vitest == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest unit tests
        run: npm run test:unit

      - name: Run Vitest coverage
        if: ${{ github.event.inputs.run_coverage == 'true' }}
        run: npm run test:coverage

      - name: Upload coverage reports
        if: ${{ github.event.inputs.run_coverage == 'true' }}
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: vitest-unit
          name: vitest-unit-coverage

  unit-tests-jest:
    name: Unit Tests (Jest)
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_jest == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Jest unit tests
        run: npm run test:unit:jest

      - name: Run Jest coverage
        if: ${{ github.event.inputs.run_coverage == 'true' }}
        run: npm run test:coverage:jest

      - name: Upload coverage reports
        if: ${{ github.event.inputs.run_coverage == 'true' }}
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: jest-unit
          name: jest-unit-coverage

  unit-tests-ava:
    name: Unit Tests (AVA)
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_ava == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run AVA unit tests
        run: npm run test:unit:ava

      - name: Run AVA coverage
        if: ${{ github.event.inputs.run_coverage == 'true' }}
        run: npm run test:coverage:ava

      - name: Upload coverage reports
        if: ${{ github.event.inputs.run_coverage == 'true' }}
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: ava-unit
          name: ava-unit-coverage



  
